### ISSUE TITLE
ridgeplot showCategory doesn't accept vector of specific pathways in enrichplot package

### ISSUE THREAD

**Issue by huerqiang** [YuLab-SMU/ProjectYulab#8]
In the enrichplot package, we have support showCategory to accept vector of specific pathways in some functions, such as dotplot() and barplot(), but not in ridgeplot(): 
https://github.com/YuLab-SMU/enrichplot/issues/193

Please support this feature request.

**Comment by l-magnificence** [comment]
In the original function ridgeplot (https://github.com/YuLab-SMU/enrichplot/blob/master/R/ridgeplot.R#L41-L46)
line 41-46
```
    n <- showCategory
    if (core_enrichment) {
        gs2id <- geneInCategory(x)[seq_len(n)]
    } else {
        gs2id <- x@geneSets[x$ID[seq_len(n)]]
    }
```
change into
```
if (class(showCategory)=="numeric") {
  n <- showCategory
  if (core_enrichment) {
    gs2id <- geneInCategory(x)[seq_len(n)]
  } else {
    gs2id <- x@geneSets[x$ID[seq_len(n)]]
  }
} else {
  if (core_enrichment) {
    gs2id <- geneInCategory(x)[showCategory]
  } else {
    gs2id <- x@geneSets[showCategory]
  }
}
```
Now we can support showCategory to accept vector of specific pathways in ridgeplot
```
library(DOSE)
library(enrichplot)
library(clusterProfiler)
data(geneList)
x <- gseDO(geneList)
ridgeplot(x,showCategory = 5)
ridgeplot(x,showCategory = c("DOID:399","DOID:612","DOID:104"))
```

**Comment by GuangchuangYu** [comment]
@guidohooiveld thanks for your feedback. this feature is now supported in devel branch.
